@host = http://127.0.0.1:5000

### Create a new item
POST {{host}}/lists
Content-Type: application/json

{
  "title": "karl",
  "user_id": 2
}

### Read all the lists of a user
GET {{host}}/lists
Content-Type: application/json

### Read a single item by id
GET {{host}}/lists/5
Content-Type: application/json


### Update an item
PUT {{host}}/lists/1
Content-Type: application/json

{
  "title": "test"
}

### Delete an item
DELETE {{host}}/lists/1
Content-Type: application/json
