@host = http://127.0.0.1:5000

### Create a new item
POST {{host}}/users
Content-Type: application/json

{
  "name": "karl",
  "email": "karlito@cit.edu",
  "password": "123456"
}

### Read the list
GET {{host}}/users
Content-Type: application/json


### Read a single item by id
GET {{host}}/users/1
Content-Type: application/json

### Read a single item by username
GET {{host}}/users/get/karlito@cit.edu
Content-Type: application/json

### Update an item
PUT {{host}}/users/1
Content-Type: application/json

{
  "name": "karlnew",
  "email": "karlnew@gmail.com",
  "password": "123456"
}


### Delete an item
DELETE {{host}}/users/1
Content-Type: application/json
